"""Data config for v13 Megadepth_Syn pose-supervised training.

Loaded by train.py / test.py via ``cfg.merge_from_file(...)`` AFTER the
LOFTR cfg (eloftr_full_v13_pose_msyn_*.py) so DATASET fields here take
precedence over anything the LOFTR cfg sets.

Pairs scene_info_0.1_0.7/*.npz (K + W2C pose + depth_paths + pair_infos)
with the Megadepth_Syn image assets (style-transferred IR + phoenix VIS).
The 145/4/4 scene-disjoint split lists are generated by
MyScripts/build_megadepth_syn_pose_splits.py and live in
data/Megadepth_Syn/index/trainvaltest_list_pose/.

NOTE: every key set here must already exist in src/config/default.py
or it's added there (see MSYN_POSE_CROSS_MODAL_MODE just below METU
options); yacs raises KeyError on merge for unknown keys.
"""
from configs.data.base import cfg


SYN_PATH = "data/Megadepth_Syn"
INDEX_PATH = f"{SYN_PATH}/index"

# 1. data source -- routed by src/loftr/utils/supervision.py + src/lightning/data.py
#    to spvs_coarse (pose-based), NOT spvs_coarse_roadscene (H-based).
cfg.DATASET.TRAINVAL_DATA_SOURCE = "Megadepth_Syn_Pose"
cfg.DATASET.TEST_DATA_SOURCE = "Megadepth_Syn_Pose"

# 2. train / val / test list + per-npz scene_info root
cfg.DATASET.TRAIN_DATA_ROOT = SYN_PATH
cfg.DATASET.TRAIN_NPZ_ROOT = f"{INDEX_PATH}/scene_info_pose"
cfg.DATASET.TRAIN_LIST_PATH = f"{INDEX_PATH}/trainvaltest_list_pose/train_list_pose.txt"
cfg.DATASET.TRAIN_INTRINSIC_PATH = None
cfg.DATASET.TRAIN_POSE_ROOT = None

cfg.DATASET.VAL_DATA_ROOT = SYN_PATH
cfg.DATASET.VAL_NPZ_ROOT = f"{INDEX_PATH}/scene_info_pose"
cfg.DATASET.VAL_LIST_PATH = f"{INDEX_PATH}/trainvaltest_list_pose/val_list_pose.txt"
cfg.DATASET.VAL_INTRINSIC_PATH = None
cfg.DATASET.VAL_POSE_ROOT = None

cfg.DATASET.TEST_DATA_ROOT = SYN_PATH
cfg.DATASET.TEST_NPZ_ROOT = f"{INDEX_PATH}/scene_info_pose"
cfg.DATASET.TEST_LIST_PATH = f"{INDEX_PATH}/trainvaltest_list_pose/test_list_pose.txt"
cfg.DATASET.TEST_INTRINSIC_PATH = None
cfg.DATASET.TEST_POSE_ROOT = None

# 3. overlap threshold
# LoFTR scene_info_0.1_0.7 buckets pair_infos by overlap [0.1, 0.3), [0.3, 0.5),
# [0.5, 0.7) at the source level (filename suffix). Setting 0.0 here means
# accept every pair the npz holds; LoFTR convention for MegaDepth training.
cfg.DATASET.MIN_OVERLAP_SCORE_TRAIN = 0.0
cfg.DATASET.MIN_OVERLAP_SCORE_TEST = 0.0

# 4. MegaDepth-style image / depth knobs (matches outdoor.ckpt training domain).
# DEFAULT in src/config/default.py is (640, 8), MUST override here or
# scale0/scale1 will be wrong and pose AUC will collapse.
cfg.DATASET.MGDPT_IMG_RESIZE = 832
cfg.DATASET.MGDPT_DF = 32
cfg.DATASET.MGDPT_IMG_PAD = True
cfg.DATASET.MGDPT_DEPTH_PAD = True

# 5. Cross-view cross-modal direction. 'ir2vis' = image0=IR(idx0),
# image1=VIS(idx1), matches v0..v11 + METU_VISTIR training-side
# convention (image0=thermal). v13 main run only uses 'ir2vis'.
cfg.DATASET.MSYN_POSE_CROSS_MODAL_MODE = "ir2vis"

# 6. Per-dataset name used by src/loftr/utils/position_encoding.py for the
# NPE (NeighbourPositionalEncoding) presets. We borrow 'megadepth' because
# v13 image shapes / scale conventions are identical (MegaDepth-style).
cfg.DATASET.NPE_NAME = "megadepth"
